apiVersion: apps/v1
kind: Deployment
metadata:
  name: piep-redis-deployment
spec:
  selector:
    matchLabels:
      app: piep-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: piep-redis
    spec:
      containers:
      - name: piep-redis
        image: ralfluebben/piep-redis:1.27
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 100m
        env:
        - name: db_addr
          value: "g2-mongoservice-ms11.wi.fh-flensburg.de"
